# Basics

In [1]:
print("Hello")

Hello


In [2]:
a = 5
print(a)

5


In [3]:
#This is a comment
a = 10 
print(a)
print(type(a))

10
<class 'int'>


In [4]:
a = 1.5
print(a)
print(type(a))

1.5
<class 'float'>


In [5]:
a = 1 + 5j
print(a)
print(type(a))

(1+5j)
<class 'complex'>


In [6]:
a = 'Welcome to ML Lab'
print(a)
print(type(a))

Welcome to ML Lab
<class 'str'>


In [7]:
a = "Welcome to ML Lab"
print(a)
print(type(a))

Welcome to ML Lab
<class 'str'>


In [8]:
a = '''
I hope you are 
enjoying the class
'''
print(a)
print(type(a))


I hope you are 
enjoying the class

<class 'str'>


In [9]:
a = """
I hope you are 
enjoying the class
"""
print(a)
print(type(a))


I hope you are 
enjoying the class

<class 'str'>


In [10]:
a,b,c = 10,20,30.34
print(a,b,c)

10 20 30.34


### List, Tupple, Dict in Python

In [11]:
l = [10, 20, 30]
print(l)
print(type(l))

[10, 20, 30]
<class 'list'>


In [12]:
fruits = ["apple", "mango", "banana"]
print(fruits)

['apple', 'mango', 'banana']


In [13]:
t = (10, 60, 80)
print(t)
print(type(t))

(10, 60, 80)
<class 'tuple'>


In [14]:
d = {'apple' : 20 , 'mango' : 30 , 'banana' : 100}
print(d)
print(type(d))

{'apple': 20, 'mango': 30, 'banana': 100}
<class 'dict'>


### Operators

In [15]:
a = 10
b = 20

print(a+b)
print(a-b)
print(a*b)
print(a/b)
print(a//b)
print(b**a) # b^a

a = 24
b = 5
print(a%b)

30
-10
200
0.5
0
10240000000000
4


### Conditional Statements

In [16]:
a = 0
if a > 0 :
    print("positive")
    print("i am here in if block")
elif a < 0 :
    print("negative")
else :
    print("zero")

zero


### Loop

In [17]:
i = 1
while i <= 10 :
    print(i)
    i += 1

1
2
3
4
5
6
7
8
9
10


In [18]:
x = range(1,20,3)
print(list(x))

[1, 4, 7, 10, 13, 16, 19]


In [19]:
for i in range(10) :
    print(i)

0
1
2
3
4
5
6
7
8
9


In [20]:
for i in range(5,20,4) :
    print(i)

5
9
13
17


In [21]:
fruits = ["apple", "mango", "banana"]
for i in fruits :
    print(i)

apple
mango
banana


## Numpy

In [22]:
import numpy as np

In [23]:
arr = np.array([1,2,3,4,5])
print(arr)
print(type(arr))
print(arr.shape)
print(arr[3])

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)
4


In [24]:
arr2 = np.array([[1],[2],[3],[4],[5]])
print(arr2)
print(arr2.shape)

[[1]
 [2]
 [3]
 [4]
 [5]]
(5, 1)


In [25]:
arr2 = np.array([[1,2,3,4],[5,6,7,8]])
print(arr2)
print(arr2.shape)
print(arr2[1][2])

[[1 2 3 4]
 [5 6 7 8]]
(2, 4)
7


In [26]:
arr = np.zeros((3,3))
print(arr)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [27]:
arr = np.zeros((3,3), dtype = np.int64)
print(arr)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [28]:
arr = np.ones((2,3), dtype = np.int64)
print(arr)

[[1 1 1]
 [1 1 1]]


In [29]:
arr = np.full((2,3), 5)
print(arr)

[[5 5 5]
 [5 5 5]]


In [30]:
arr = np.eye(4)
print(arr)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [31]:
rm = np.random.random((3,5))
print(rm)

[[0.22257491 0.61538473 0.01911886 0.05060099 0.81696332]
 [0.91454112 0.5920128  0.00927942 0.74589767 0.37884545]
 [0.45199812 0.53341647 0.04570941 0.78460323 0.79096119]]


In [32]:
rm[: , 1] = 10
print(rm)

[[2.22574908e-01 1.00000000e+01 1.91188566e-02 5.06009934e-02
  8.16963321e-01]
 [9.14541122e-01 1.00000000e+01 9.27942365e-03 7.45897674e-01
  3.78845448e-01]
 [4.51998115e-01 1.00000000e+01 4.57094112e-02 7.84603230e-01
  7.90961192e-01]]


In [33]:
rm[1:,:2] = 20
print(rm)

[[2.22574908e-01 1.00000000e+01 1.91188566e-02 5.06009934e-02
  8.16963321e-01]
 [2.00000000e+01 2.00000000e+01 9.27942365e-03 7.45897674e-01
  3.78845448e-01]
 [2.00000000e+01 2.00000000e+01 4.57094112e-02 7.84603230e-01
  7.90961192e-01]]


In [34]:
arr = np.zeros((3,3), dtype = np.int64)
print(arr)
arr[1,:] = 5
arr[:,-1] = 7
print(arr)
print(arr.dtype)

[[0 0 0]
 [0 0 0]
 [0 0 0]]
[[0 0 7]
 [5 5 7]
 [0 0 7]]
int64


In [35]:
x = np.array([[1,2,3],[4,5,6],[7,8,9]])
y = np.array([[7,8,9],[10,11,12],[13,14,25]])

In [36]:
#Add
print(x+y)
print(np.add(x,y))

[[ 8 10 12]
 [14 16 18]
 [20 22 34]]
[[ 8 10 12]
 [14 16 18]
 [20 22 34]]


In [37]:
#Subtraction
print(x-y)
print(np.subtract(x,y))

[[ -6  -6  -6]
 [ -6  -6  -6]
 [ -6  -6 -16]]
[[ -6  -6  -6]
 [ -6  -6  -6]
 [ -6  -6 -16]]


In [38]:
#Multiply
print(x*y)
print(np.multiply(x,y))

[[  7  16  27]
 [ 40  55  72]
 [ 91 112 225]]
[[  7  16  27]
 [ 40  55  72]
 [ 91 112 225]]


In [39]:
#Divide
print(x/y)
print(np.divide(x,y))

[[0.14285714 0.25       0.33333333]
 [0.4        0.45454545 0.5       ]
 [0.53846154 0.57142857 0.36      ]]
[[0.14285714 0.25       0.33333333]
 [0.4        0.45454545 0.5       ]
 [0.53846154 0.57142857 0.36      ]]


In [40]:
print(np.sqrt(x))

[[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]
 [2.64575131 2.82842712 3.        ]]


In [41]:
print(x.dot(y))
print(np.dot(x,y))

[[ 66  72 108]
 [156 171 246]
 [246 270 384]]
[[ 66  72 108]
 [156 171 246]
 [246 270 384]]


In [42]:
a = np.array([1,2,3,4,5])
b = np.array([1,2,3,4,5])
print(a.dot(b))

55


In [43]:
arr = np.array([1,2,3,4,5])
print(arr)
print(arr+4)

[1 2 3 4 5]
[5 6 7 8 9]


In [44]:
arr2 = np.array([[10,20,30,40,50],[60,70,80,90,100]])
print(arr2)
print(arr2+arr)

[[ 10  20  30  40  50]
 [ 60  70  80  90 100]]
[[ 11  22  33  44  55]
 [ 61  72  83  94 105]]


In [45]:
arr = np.array([1,2,3,4,5])
print(sum(arr))
print(np.sum(arr))

15
15


In [46]:
arr2 = np.array([[10,20,30,40,50],[60,70,80,90,100]])
print(arr2)
print(np.sum(arr2, axis = 0)) # sum column wise
print(np.sum(arr2, axis = 1)) # sum row wise

[[ 10  20  30  40  50]
 [ 60  70  80  90 100]]
[ 70  90 110 130 150]
[150 400]


In [47]:
a = np.array([1,2,3,4])
b = np.array([1,2,3,4])
print(a)
print(b)
b = b * 2
print(b)
b = b ** 2
print(b)

[1 2 3 4]
[1 2 3 4]
[2 4 6 8]
[ 4 16 36 64]


In [48]:
s = np.stack((a,b), axis = 0)
print(s)
s = np.stack((a,b), axis = 1)
print(s)

[[ 1  2  3  4]
 [ 4 16 36 64]]
[[ 1  4]
 [ 2 16]
 [ 3 36]
 [ 4 64]]


In [49]:
print(s)
s = s.reshape((4,2))
print(s)

[[ 1  4]
 [ 2 16]
 [ 3 36]
 [ 4 64]]
[[ 1  4]
 [ 2 16]
 [ 3 36]
 [ 4 64]]


In [50]:
s = s.reshape((-1,4))
print(s)

[[ 1  4  2 16]
 [ 3 36  4 64]]


In [51]:
a = np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [52]:
a = np.arange(10) + 5
print(a)

[ 5  6  7  8  9 10 11 12 13 14]


In [53]:
arr = [5, 6, 7,  8,  9, 10, 11, 12, 13, 14]
np.random.seed(1)
np.random.shuffle(arr)
print(arr)

[7, 14, 11, 9, 5, 8, 6, 12, 13, 10]


In [54]:
arr = np.random.rand(2,3)
print(arr)

[[0.38791074 0.66974604 0.93553907]
 [0.84631092 0.31327352 0.52454816]]


In [55]:
arr = np.random.randn(2,3)
print(arr)

[[-1.50780766 -0.31529207  0.85817886]
 [ 0.07134299 -2.29230928 -1.41555249]]


In [56]:
arr = np.random.randint(5, 20, 4)
print(arr)

[19  5 11 18]


In [57]:
element = np.random.choice([1,4,3,2,11,27])
print(element)

4
